<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
    <line>
      <![CDATA[1495007834226]]>
    </line>
    <line>
      <![CDATA[Test Case testRavi started at Wed May 17 13:26:47 IST 2017]]>
    </line>
    <line>
      <![CDATA[Test Case testRavi failed at 17-05-2017-01-26-47 ]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="36068" started-at="2017-05-17T07:56:47Z" finished-at="2017-05-17T07:57:23Z">
    <groups>
      <group name="Smoke">
        <method signature="RaviTest.testRavi()[pri:0, instance:scripts.RaviTest@7c16905e]" name="testRavi" class="scripts.RaviTest"/>
      </group> <!-- Smoke -->
    </groups>
    <test name="Default test" duration-ms="36068" started-at="2017-05-17T07:56:47Z" finished-at="2017-05-17T07:57:23Z">
      <class name="scripts.RaviTest">
        <test-method status="PASS" signature="openApplication()[pri:0, instance:scripts.RaviTest@7c16905e]" name="openApplication" is-config="true" duration-ms="26939" started-at="2017-05-17T13:26:47Z" finished-at="2017-05-17T13:27:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApplication -->
        <test-method status="FAIL" signature="testRavi()[pri:0, instance:scripts.RaviTest@7c16905e]" name="testRavi" duration-ms="6614" started-at="2017-05-17T13:27:14Z" finished-at="2017-05-17T13:27:20Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.fail(Assert.java:101)
	at scripts.RaviTest.testRavi(RaviTest.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[1495007834226]]>
            </line>
            <line>
              <![CDATA[Test Case testRavi started at Wed May 17 13:26:47 IST 2017]]>
            </line>
            <line>
              <![CDATA[Test Case testRavi failed at 17-05-2017-01-26-47 ]]>
            </line>
          </reporter-output>
        </test-method> <!-- testRavi -->
        <test-method status="PASS" signature="closeApplication(org.testng.ITestResult)[pri:0, instance:scripts.RaviTest@7c16905e]" name="closeApplication" is-config="true" duration-ms="2442" started-at="2017-05-17T13:27:20Z" finished-at="2017-05-17T13:27:23Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testRavi status=FAILURE method=RaviTest.testRavi()[pri:0, instance:scripts.RaviTest@7c16905e] output=1495007834226]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApplication -->
      </class> <!-- scripts.RaviTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
